venv_my_cafe/my_cafe/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('news/', views.NewsView.as_view(), name="news"),
    path('products/', views.ProductsView.as_view(), name="products"),
    path('concept/', views.ConceptView.as_view(), name="concept"),
    path('faq/', views.FaqView.as_view(), name="faq"),
    path('shop/', views.ShopView.as_view(), name="shop"),
]

venv_my_cafe/my_cafe/my_cafe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

venv_my_cafe/my_cafe/main/models.py
from django.db import models

# Create your models here.

venv_my_cafe/my_cafe/main/views.py
# from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = "index.html"

class NewsView(generic.TemplateView):
    template_name = "news.html"

class ProductsView(generic.TemplateView):
    template_name = "products.html"

class ConceptView(generic.TemplateView):
    template_name = "concept.html"

class FaqView(generic.TemplateView):
    template_name = "faq.html"

class ShopView(generic.TemplateView):
    template_name = "shop.html"

venv_my_cafe/my_cafe/main/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!--Style-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
</head>

<body>
    <div id="wrapper">
        <header class="page-header wrapper">

            <nav class="main-nav">
                <a href="/" class="logo">
                  <img src="{% static 'img/logo.svg' %}" alt="MyCafe">
                </a>
                <li><a href="/">HOME<p>トップページ</p></a></li>
                <li><a href="{% url 'main:concept' %}">CONCEPT<p>コンセプト</p></a></li>
                <li><a href="{% url 'main:products' %}">PRODUCTS<p>製品情報</p></a></li>
                <li><a href="{% url 'main:faq' %}">FAQ<p>よくあるご質問</p></a></li>
                <li><a href="{% url 'main:shop' %}">SHOP<p>店内情報</p></a></li>
                <div class="onlineshop-button"><a href="#">ONLINE SHOP</a></div>
            </nav>
        </header>

        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer class="">
            <div class="onlineshop-section">
                <div class="contents-frame">
                </div>
            </div>
            <div class="footer-link">
                <div>
                    <ul class="footer-nav">
                        <li class="">
                            <a class="" href="">HOME</a>
                        </li>
                        <li class="">
                            <a class="" href="">CONCEPT</a>
                        </li>
                        <li class="">
                            <a class="" href="">PRODUCTS</a>
                        </li>
                        <li class="">
                            <a class="" href="">FAQ</a>
                        </li>
                        <li class="">
                            <a class="" href="">SHOP</a>
                        </li>
                        <li class="">
                            <a class="" href="">ONLINE SHOP</a>
                        </li>
                    </ul>
                </div>
                <p class="">Copyright © Akari organic All Rights Reserved.</p>
            </div>
        </footer>

        <script></script>

    </div>
</body>
</html>

venv_my_cafe/my_cafe/main/templates/concept.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}

<div class="r page-title">
    <div class="col-4 title">
        <p>Concept</p>

    </div>
</div>

<div class="eyecatch-image">
</div>

{% endblock %}

venv_my_cafe/my_cafe/main/templates/faq.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}

<div class="r page-title">
    <div class="col-4 title">
        <p>FAQ</p>

    </div>
</div>

<div class="eyecatch-image">
</div>

{% endblock %}

venv_my_cafe/my_cafe/main/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}

<div class="r page-title">
    <div class="col-4 title">
        <p>Concept</p>

    </div>
</div>

<div class="eyecatch-image">
</div>

<section id="home-concept">
    <h1>コンセプト</h1>
    <p class="title-border">Concept</p>
    <p class="explain-text">どなたにも安心してお使いいただくため、<br>
    数万種類以上から選び抜いたスキンケアに有効かつ安全な植物を、<br>
    自社農園で大事に育てています。<br>
    <br>
    植物の栄養をじっくりと熟成させ、<br>
    一滴一滴丁寧に抽出したエキスから生まれた<br>
    オーガニックコスメ、<br>
    「AKARI organic」。<br>
    <br>
    あなたの肌を、<br>
    本来の美しく健康な状態へ導きます。</p>
    <div class="button-area">
        <a class="btn-border" href="{% url 'main:concept' %}">
            <span>Concept</span>
        </a>
    </div>
</section>

<section id="home-about">
    <h1>MyCafeとは</h1>
    <p class="title-border">About</p>
    <div class="r">
        <div class="col-5">
            <img src="{% static 'img/menu1.jpg' %}" alt="MyCafe">
        </div>
        <div class="col-5">
            <h3>よくあるご質問</h3>
            <div class="h3-border"></div>
            <p class="explain-text">オーガニックコスメはとってもデリケートな商品のため、<br>
                正しい使い方をしないと効果が半減してしまいます。<br>
                保管方法で注意すること、使用期限、敏感肌でも安心して使える・・・？<br>
                製品に関するお客様からのご質問にお答えいたします。</p>
            <div class="button-area">
                <a class="btn-border" href="{% url 'main:faq' %}">
                    <span>FAQ</span>
                </a>
            </div>
        </div>
    </div>

    <div class="r">
        <div class="col-5">
            <h3>オリジナルショップ</h3>
            <div class="h3-border"></div>
            <p class="explain-text">AKARI organicオリジナルショップでは、製品をご購入いただける他、<br>
                オリジナル化粧品を手作りできるアロマバーをご利用いただけます。<br>
                あなたの肌質やお肌の悩み、お好みの香りに合わせ、
                <br>世界で一つだけのオリジナルブレンドオイルをおつくりいたします。</p>
            <div class="button-area">
                <a class="btn-border" href="{% url 'main:shop' %}">
                    <span>Shop</span>
                </a>
            </div>
        </div>
        <div class="col-5">
            <img src="{% static 'img/menu2.jpg' %}" alt="MyCafe">
        </div>
    </div>

</section>

<section id="home-products">
    <h1>商品一覧</h1>
    <p class="title-border">products</p>
    <div class="r">
        <div class="col-3">
            <a href="#">
            <img src="{% static 'img/menu3.jpg' %}" alt="MyCafe">
            </a>
            <p class="explain-text">商品A</p>
        </div>
        <div class="col-3">
            <a href="#">
            <img src="{% static 'img/menu4.jpg' %}" alt="MyCafe">
            </a>
            <p class="explain-text">商品A</p>
        </div>
        <div class="col-3">
            <a href="#">
            <img src="{% static 'img/menu5.jpg' %}" alt="MyCafe">
            </a>
            <p class="explain-text">商品A</p>
        </div>
    </div>
    <div class="button-area">
        <a class="btn-border" href="{% url 'main:products' %}">
            <span>Products</span>
        </a>
    </div>
</section>

{% endblock %}

venv_my_cafe/my_cafe/main/templates/news.html
<!DOCTYPE html>

{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>WCB Cafe - NEWS</title>
    <meta name="description" content="ブレンドコーヒーとヘルシーなオーガニックフードを提供するカフェ">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<!-- CSS -->
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
    <div id="news" class="big-bg">
        <header class="page-header wrapper">
            <h1><a href="{% url 'main:index' %}"><img class="logo" src="{% static 'img/logo.svg' %}" alt="WCBカフェ ホーム"></a></h1>
            <nav>
                <ul class="main-nav">
                    <li><a href="{% url 'main:news' %}">News</a></li>
                    <li><a href="{% url 'main:menu' %}">Menu</a></li>
                    <li><a href="{% url 'main:contact' %}">Contact</a></li>
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            <h2 class="page-title">News</h2>
        </div><!-- /.wrapper -->
    </div>

    <div class="news-contents wrapper">
        <article>
            <header class="post-info">
                <h2 class="post-title">店内ギャラリーの絵が新しくなりました</h2>
                <p class="post-date">3/30 <span>2019</span></p>
                <p class="post-cat">カテゴリー：お店の紹介</p>
            </header>
            <img src="{% static 'img/wall.jpg' %}" alt="店内の様子">
            <p>
                体に優しい自然食を提供する、WCB CAFE。無添加の食材を利用したメニューが特徴です。
                美味しいブレンドコーヒーとヘルシーなオーガニックフードで体の内側から癒やされてください。
            </p>
            <p>
                体に優しい自然食を提供する、WCB CAFE。無添加の食材を利用したメニューが特徴です。
                美味しいブレンドコーヒーとヘルシーなオーガニックフードで体の内側から癒やされてください。
            </p>
            <p>
                体に優しい自然食を提供する、WCB CAFE。
            </p>
        </article>

        <aside>
            <h3 class="sub-title">カテゴリー</h3>
            <ul class="sub-menu">
                <li><a href="#">お店の紹介</a></li>
                <li><a href="#">期間限定メニュー</a></li>
                <li><a href="#">イベント</a></li>
                <li><a href="#">お客様との会話</a></li>
            </ul>

            <h3 class="sub-title">このお店について</h3>
            <p>
                体に優しい自然食を提供する、WCB CAFE。無添加の食材を利用したメニューが特徴です。
                美味しいブレンドコーヒーとヘルシーなオーガニックフードで体の内側から癒やされてください。
            </p>
        </aside>

        <div class="ad">
            <img src="{% static 'img/banner.jpg' %}" alt="新メニュー登場">
        </div>
    </div><!-- /.news-contents -->

    <footer>
        <div class="wrapper">
            <p><small>&copy; 2020 hoge</small></p>
        </div>
    </footer>
</body>

</html>

venv_my_cafe/my_cafe/main/templates/products.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}

<div class="r page-title">
    <div class="col-4 title">
        <p>Products</p>

    </div>
</div>

<div class="eyecatch-image">
</div>

{% endblock %}

venv_my_cafe/my_cafe/main/templates/shop.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}

<div class="r page-title">
    <div class="col-4 title">
        <p>Shop</p>

    </div>
</div>

<div class="eyecatch-image">
</div>

{% endblock %}